import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

export const THEME = {
  light: {
    background: 'hsl(0 0% 100%)',
    foreground: 'hsl(0 0% 4%)',
    card: 'hsl(0 0% 100%)',
    cardForeground: 'hsl(0 0% 4%)',
    popover: 'hsl(0 0% 100%)',
    popoverForeground: 'hsl(0 0% 4%)',
    primary: 'hsl(0 0% 4%)',
    primaryForeground: 'hsl(0 0% 100%)',
    secondary: 'hsl(0 0% 96%)',
    secondaryForeground: 'hsl(0 0% 4%)',
    muted: 'hsl(0 0% 96%)',
    mutedForeground: 'hsl(0 0% 45%)',
    accent: 'hsl(0 0% 96%)',
    accentForeground: 'hsl(0 0% 4%)',
    destructive: 'hsl(0 84% 60%)',
    border: 'hsl(0 0% 90%)',
    input: 'hsl(0 0% 90%)',
    ring: 'hsl(0 0% 4%)',
    radius: '0.5rem',
    success: 'hsl(142 71% 45%)',
    streak: 'hsl(25 95% 53%)',
  },
  dark: {
    background: 'hsl(0 0% 4%)',
    foreground: 'hsl(0 0% 98%)',
    card: 'hsl(0 0% 8%)',
    cardForeground: 'hsl(0 0% 98%)',
    popover: 'hsl(0 0% 8%)',
    popoverForeground: 'hsl(0 0% 98%)',
    primary: 'hsl(0 0% 98%)',
    primaryForeground: 'hsl(0 0% 4%)',
    secondary: 'hsl(0 0% 14%)',
    secondaryForeground: 'hsl(0 0% 98%)',
    muted: 'hsl(0 0% 14%)',
    mutedForeground: 'hsl(0 0% 55%)',
    accent: 'hsl(0 0% 14%)',
    accentForeground: 'hsl(0 0% 98%)',
    destructive: 'hsl(0 84% 60%)',
    border: 'hsl(0 0% 16%)',
    input: 'hsl(0 0% 16%)',
    ring: 'hsl(0 0% 98%)',
    radius: '0.5rem',
    success: 'hsl(142 71% 45%)',
    streak: 'hsl(25 95% 53%)',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
